id: P006657
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20468
  title: ཀློང་ཆེན་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    016d30e6398547caa9adc354bc8bf684:
      image_group_id: I1GS105496
      title: ''
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
